#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-CleanNameSpaces
Version  : 0.23
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Test-CleanNamespaces-0.23.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Test-CleanNamespaces-0.23.tar.gz
Summary  : 'Check for uncleaned imports'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Test-CleanNameSpaces-data = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(File::pushd)
BuildRequires : perl(Module::Runtime)
BuildRequires : perl(Package::Stash)
BuildRequires : perl(Sub::Exporter)
BuildRequires : perl(Sub::Identify)
BuildRequires : perl(Test::Deep)
BuildRequires : perl(Test::Needs)
BuildRequires : perl(Test::Warnings)
BuildRequires : perl(namespace::clean)

%description
This archive contains the distribution Test-CleanNamespaces,
version 0.23:
Check for uncleaned imports

%package data
Summary: data components for the perl-Test-CleanNameSpaces package.
Group: Data

%description data
data components for the perl-Test-CleanNameSpaces package.


%package dev
Summary: dev components for the perl-Test-CleanNameSpaces package.
Group: Development
Requires: perl-Test-CleanNameSpaces-data = %{version}-%{release}
Provides: perl-Test-CleanNameSpaces-devel = %{version}-%{release}

%description dev
dev components for the perl-Test-CleanNameSpaces package.


%prep
%setup -q -n Test-CleanNamespaces-0.23

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Test-CleanNameSpaces
cp LICENCE %{buildroot}/usr/share/package-licenses/perl-Test-CleanNameSpaces/LICENCE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.26.1/Test/CleanNamespaces.pm

%files data
%defattr(-,root,root,-)
/usr/share/package-licenses/perl-Test-CleanNameSpaces/LICENCE

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Test::CleanNamespaces.3
